version: "3.8"

services:
    webscraper:
      build:
        context: ../
        target: Development
      volumes:
        - ${PWD}:/app
      image: webscraper
      container_name: webscraper
      networks:
        - webscraper
